name: CI
on:
  push:
env:
  UNIFFI_VERSION: 0.8.0
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Restore Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install uniffi-bindgen
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version ${{ env.UNIFFI_VERSION }} uniffi_bindgen
      - name: Run check
        run: cd android && ./gradlew check
  connected-check:
    name: Connected check
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Restore Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install uniffi-bindgen
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version ${{ env.UNIFFI_VERSION }} uniffi_bindgen
      - name: Run connectedCheck
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          ndk: 21.4.7075529
          script: cd android && ./gradlew connectedCheck
