[package]
name = "bend_j4rs"
version = "1.0.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
bend = { path = "../" }
j4rs = "0.13.0"
j4rs_derive = "0.1.0"
log = { version = "0.4.14", features = ["release_max_level_off"] }
