[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both", "-C", "link-arg=-ldl"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both", "-C", "link-arg=-ldl"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both", "-C", "link-arg=-ldl"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both", "-C", "link-arg=-ldl"]
